steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/kcmd-docker-repo/kcmd-sync-service:latest',
    '-f', 'kcmd-sync-service/Dockerfile',
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/kcmd-docker-repo/kcmd-sync-service:latest'
